[package]

name = "differential-dataflow"
version = "0.2.0"
authors = ["Frank McSherry <fmcsherry@me.com>"]

description = "An incremental data-parallel dataflow platform"

# These URLs point to more information about the repository
documentation = "https://github.com/frankmcsherry/differential-dataflow"
homepage = "https://github.com/frankmcsherry/differential-dataflow"
repository = "https://github.com/frankmcsherry/differential-dataflow.git"
keywords = ["differential", "dataflow"]
license = "MIT"

[dependencies.graph_map]
git="https://github.com/frankmcsherry/graph-map.git"

[dev-dependencies]
getopts="0.2.14"
rand="0.3.13"
byteorder="0.4.2"
itertools="^0.6"

[dependencies]
abomonation = { git = "https://github.com/frankmcsherry/abomonation" }
abomonation_derive = { git = "https://github.com/mystor/abomonation_derive" }
timely_sort="0.1.6"
timely_communication = { git = "https://github.com/frankmcsherry/timely-dataflow" }
timely = { git = "https://github.com/frankmcsherry/timely-dataflow" }
#timely_communication = { path = "../timely-dataflow/communication" }
#timely = { path = "../timely-dataflow/" }
fnv="1.0.2"

[features]
default = []
#logging = ["timely/logging"]

[profile.release]
opt-level = 3
debug = true
rpath = false
lto = false
debug-assertions = false
